name: Baseline Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  baseline-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Checkout the PR branch

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run basic tests
        run: npm test -- userController.test.js
