name: Daily Test and Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC

  pull_request:
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run all unit tests
        run: npm test